spring:
  data:
    r2dbc:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
  r2dbc:
    url: r2dbc:mysql://192.168.71.73:3306/ox
    username: root
    password: 123456
  elasticsearch:
    username: elastic
    password: 4dS0Yn7UXyON*eYvISa=
    uris: http://192.168.71.73:9200


